services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - PORT=8000
      - MODEL_PATH=models/lightgbm_life_expectancy.pkl
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8501
      - MODEL_PATH=models/lightgbm_life_expectancy.pkl
    ports:
      - "8501:8501"
